config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :teams, only: [:index, :show, :new, :create] do
    resources :players, only: [:show, :new, :create]
  end

  resources :players, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team

  validates :name, presence: true, length: { in: 1..50 }
  validates :gender, presence: true

  enum gender: { unknown: 0, male: 1, female: 2 }
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players, dependent: :destroy

  validates :name, presence: true, length: { in: 1..50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find_by(id: params[:id])
  end

  def new
    @team ||= Team.find_by(id: params[:team_id])
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @team = Team.find_by(id: params[:team_id])
    if @player.save
      redirect_to team_player_url(@team, @player)
    else
      render "new", { team: @team }
    end
  end

  def player_params
    params.require(:player).permit(:name, :team_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find_by(id: params[:id])
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to @team
    else
      render "new"
    end
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails71</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<div>
  <h1>選手一覧</h1>
  <% if @players.present? %>
    <ul>
      <% @players.each do |player| %>
        <li><%= link_to player.name, team_player_url(player.team_id, player.id) %></li>
      <% end %>
    </ul>
  <% else %>
    <div>選手が登録されていません。</div>
  <% end %>
  <%= link_to "参加チーム一覧", teams_url %>
</div>

app/views/players/new.html.erb
<div>
  <h1><%= @team.name%>への選手登録</h1>
  <%= form_with(model:[@team, @player], local: true) do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.hidden_field :team_id, :value => @team.id %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
  <%= link_to "#{@team.name}のページに戻る", team_url(@team) %>
</div>

app/views/players/show.html.erb
<div>
  <h1>選手情報</h1>
  <p>選手名: <%= @player.name %></p>
  <p>所属チーム: <%= link_to @player.team.name, team_url(@player.team_id) %></p>
  <%= link_to "選手一覧", players_url %>
</div>